print('*******************************************************************************')
print('          |                   |                  |                     |')
print('_________|________________.=""_;=.______________|_____________________|_______')
print('|                   |  ,-"_,=""     \'"=.|                  |')
print('|___________________|__"=._o\'"-._        \'"=.______________|___________________')
print('          |                \'"=._o\'"=._      _\'"=._                     |')
print('_________|_____________________:=._o "=._."_.-="\'"=.__________________|_______')
print('|                   |    __.--" , ; \'"=._o." ,-"""-._ ".   |')
print('|___________________|_._"  ,. .\' \' \'\' ,  \'"-._"-._   ". \'__|___________________')
print('          |           |o\'"=._\' , "\' \'; .". ,  "-._"-._; ;              |')
print('_________|___________| ;\'-.o\'"=._; ." \' \'\'."\' . "-._ /_______________|_______')
print('|                   | |o;    \'"-.o\'"=._\'\'  \'\' " ,__.--o;   |')
print('|___________________|_| ;     (#) \'-.o \'"=.\'_.--"_o.-; ;___|___________________')
print('____/______/______/___|o;._    "      \'".o|o_.--"    ;o;____/______/______/____')
print('/______/______/______/_"=._o--._        ; | ;        ; ;/______/______/______/_')
print('____/______/______/______/__"=._o--._   ;o|o;     _._;o;____/______/______/____')
print('/______/______/______/______/____"=._o._; | ;_.--"o.--"_/______/______/______/_')
print('____/______/______/______/______/_____"=.o|o_.--""___/______/______/______/____')
print('/______/______/______/______/______/______/______/______/______/______/_____ /')
print('*******************************************************************************')
print('Welcome to Treasure Island.')
print('Your mission is to find the treasure.')

print("You're at a cross road. Where do you want to go?")
# cross_road = input('\tType "left" or "right"\n')
user_input = input('\tType "left" or "right"\n')
cross_road = user_input.lower()
if cross_road == 'right':
    print("You fell into a hole. Game Over.")
elif cross_road == 'left':
  print("You've come to a lake. There is an island in the middle of the lake.")
  user_input = input('\tType "wait" to wait for a boat. Type "swim" to swim across.\n')
  lake = user_input.lower()
  if lake == "wait":
      print("You arrive at the island unharmed. There is a house with 3 doors.")
      user_input = input('\tOne red, one yellow and one blue. Which colour do you choose?\n')
      door = user_input.lower()
      if door == "red":
          print("It's a room full of fire. Game Over.")
      elif door == "yellow":
          print("You found the treasure! You Win!")
      elif door == "blue":
          print("You enter a room of beasts. Game Over.")
  elif lake == "swim":
      print("You get attacked by an angry trout. Game Over.")